### ISSUE TITLE
Notice: Undefined index: class in [...]\DependencyInjection\AlcalynPayplugExtension.php line 29

### ISSUE THREAD

**Issue by mouts** [alcalyn/payplug-bundle#1]
Fixed by adding the missing parameter "class" with no value in the config.yml file :

``` yml
alcalyn_payplug:
    account:
        url:                %payplug_account_url%
        [...]
    class: ~
```

But I think there is a better way by editing the configuration class, like that : 

``` php
->arrayNode('class')
    ->addDefaultsIfNotSet()
    ->children()
        ->scalarNode('ipn')->defaultValue(IPN::getClassName())->end()
     ->end()
->end()
```

Thanks for this bundle !
