### ISSUE TITLE
The mapping parameters are not considered

### ISSUE THREAD

**Issue by mouts** [alcalyn/payplug-bundle#2]
The bundle use [DoctrineOrmMappingsPass](https://github.com/doctrine/DoctrineBundle/blob/v1.3.0-beta1/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php) class that's not provided by the latest stable version of DoctrineBundle (1.2.0). The [symfony documentation](http://symfony.com/doc/current/cookbook/doctrine/mapping_model_classes.html) says that DoctrineBundle supports it from version 1.2.1 but this version does not exists. Symfony documentation also says that you can provide a copy of the compiler pass, like FOSUserBundle. I can work on it.

Another way : let the user decide if he wants to use mapping parameters by editing its config file like that : 

``` yml
doctrine:
    [...]
    orm:
       [...]
        mappings:
            AlcalynPayplugBundle:
                is_bundle: true
                type: yml 
                prefix: Alcalyn\PayplugBundle\Model
                dir: Resources/config/doctrine/model
```

In this case, maybe you should add some informations in the configuration guide.

Or maybe there is a better solution...

Hope I can help !
